name: Bump

on:
  push:
    branches: [canary]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  bump:
    runs-on: depot-ubuntu-22.04-2
    timeout-minutes: 20
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
        with:
          fetch-depth: 1
      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: 22
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - name: Create version packages PR
        uses: changesets/action@63a615b9cd06ba9a3e6d13796c7fbcb080a60a0b
        with:
          version: pnpm run version
          title: "chore: version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
